# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35f825948dc3f1f17344151c14edc6fbda69db61789af360b4f84c59019f6630fdc3fa7d1f7454328d670bae183d3c53ec9d3c44eca63aede4423fa347300868

test:
  secret_key_base: 8bb6b3707aed301b692ffd1f87324a3482053677c73203d8d949d1865313448821aa7e60d4236f00c8c66971c7b4c1aab2597994d54605cee2a0b85f12aaf69d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
